/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package ConnectMySQL;

import java.util.Scanner;
import ConnectMySQL.InsertClass;
import ConnectMySQL.ReturnClass;
import eirvidprototype.CSVFileProcessor;
import eirvidprototype.PasswordGenerator;

/**
 *
 * @author Lucresse Pearle Tchatchoua Mbakop- 2021404
 * @Adjustment Renan Gomes - 2020295
 * Merge of UI class from Carol with registrationData class.
 * 
 */
public class registrationData {
     public static void menu()  {
         try{
         System.out.println("Welcome to RTE Rental System");
         System.out.println("Please select One option");
         System.out.println("1-Register");
         System.out.println("2-Log in");
         System.out.println("0-Exit");
         // THIS CODE , ASK THE SOME INPUTS TO THE USER
          Scanner scan = new Scanner(System.in);// CREATE A SCANNER TO BE ABLE TO STORE THE USER SELECTION
          int option= scan.nextInt();// PARSE THE USER SELECTION INTO A VARIABLE
          
          switch (option) {
              case 0:
                  System.out.println("Bye");// IN CASE THE USER WANT TO EXIT THE PROGRAM
                  break;// BREAK IS USE TO STOP THE IMPLEMENTATION OF THE PROGRAM
              case 1:
                  register();// THE REGISTER METHOD IS CALLED
                  break;
              case 2:
                  logIn();// THE LOGIN METHOD IS CALL TO TAKE IN THE USER INFORMATION
                  break;
          }
         }
         catch (Exception e) {
            System.out.println("please choose one of the option above ");// THE ExceptION ,IN THE CASE NO SELECTION IS MADE BY THE USER
        }
         
    
    }
   
     public static void logIn()  {// THE LOGIN METHOD IS CREATED 
        try {
            Scanner scan = new Scanner(System.in);// CREATE A SCANNER TO TAKE THE USER INPUT 
            System.out.println("----------------------------------------");
            System.out.println("Welcome dear Customer");//
            System.out.println("----------------------------------------");
            System.out.println("Enter your email ");
            String email = scan.next();// STORE THE USER EMAIL INTO A VARIABLE
            System.out.println("Enter your Password ");
           String password = scan.next();// 
           ReturnClass.searchByEmail(email);// RETURN THE USER HISTORY 
           
        } catch (Exception e) {
            System.out.println(" Your informations are not found in our system");

        }
    }
     
      public static void register() {// CREATE A METHOD 
        try {
           
         do {
             Scanner userInput = new Scanner (System.in);
             System.out.println("Do you want to Register on EirVid?");
             System.out.println("TYPE ONLY NUMERICAL DATA! ");
             System.out.println("1 for YES or 2 for NO:");
             String opreg = userInput.nextLine();
            
//REGISTER USER

                 switch (opreg) {
    //If the user type 1 the registration will be done 
                     case "1":
                         Scanner userinput2 = new Scanner(System.in);
                         System.out.println("NAME: ");
                         String name = userinput2.nextLine();
                         System.out.println("E-MAIL: ");
                         String email = userinput2.nextLine();
                         String EMAIL_REGEX = "^[\\w-_\\.+]*[\\w-_\\.]\\@([\\w]+\\.)+[\\w]+[\\w]$";
    //Verify if it is a valid email input
                         Boolean e = email.matches(EMAIL_REGEX);
                         int selectedMovieId = 1000000000;
                         
   //If it is a valid email input the system will generate a random password                        
                         if(e==true){
   //Output the password generated by the PasswordGenerator class   
   
                             String password = PasswordGenerator.createPassword(8);
                             System.out.println("Welcome to EirVid! Your password is: " + password );
                             
                             InsertClass.insertInformation(name, email, password);
                             
                             boolean movieLocate = false;
                             
                             while(selectedMovieId != 0 && !movieLocate){
                                 System.out.println("Choose a movie from our list typing the ID:");
   //Display the movie list                              
                                 CSVFileProcessor csv = new CSVFileProcessor();
                                 csv.CSVFileProcessor();
                                 
                                 System.out.println("Type the movie ID:");
                                
                                 selectedMovieId = userInput.nextInt();
    //If the input for select a movie ID is not 0 or a movie that is not on the list the system will display the receipt                             
                                 System.out.println("----------------------RECEIPT--------------------");
                                 movieLocate = csv.FindMovieById(selectedMovieId);
                                 System.out.println("User: " + name);
                                 ReturnClass recordID = new ReturnClass();
                                 String record = recordID.returnMovieID();
                                 ReturnClass.rentExpire(record);
                                 System.out.println("-------------------------------------------------");
                                 

                              
                             }
                                                         
                        }else{
   //If the email chose by the user doesn't follow an e-mail pattern system will out put the following                   
                             System.out.println("Type a valid e-mail.");
                             register();// THIS IMPLEMENTS THE METHOD AGAIN , IN CASE THE INPUT DOES NOT MATCH THE PROGRAM EXPECTED VALUES
                         }           
                     case "2":
                         System.out.println("See you soon!");
                         break;
                         
                     default:
                         System.out.println("Please type only numerical data between 1 to 2.");
                         break;
                               }
        }while (false);
 

//            System.out.println("Enter your Password ");
//           String password = scan.next();           
//           System.out.println("Retype  your Password ");
//           String password1 = scan.next();
//            if(password1.equals(password)){
//             System.out.println(" similar");
//             
//                System.out.println(name);
//                System.out.println(email);
//                System.out.println(password);
//                
//                InsertClass.insertInformation(name, email, password);
//               //logIn();
//            }else{
//            System.out.println("not  similar");
//            }
           
        } catch (Exception e) {
            System.out.println(" Your informations are not found in our system");

        }
    }
    
}
